sudo: false

language: node_js

node_js:
- "10"
- "9"
- "8"
- "7"
- "6"
- "4"
- "0.10"

compiler:
- clang
- gcc

before_install:
- npm install node-gyp -g

install:
- npm run compile

before_script:
- node-gyp clean
